spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dormdb
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
jwt:
  secret: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
  expirationMs: 36000000