# This workflow deploys the Spring Boot app to your server when you push to the main branch
name: Deploy Spring Boot App

on:
  push:
    branches: [ "main" ] # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # The pipeline runs on a fresh Ubuntu machine

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 3. Build the JAR file
        run: mvn -B package --file pom.xml

      - name: 4. Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: 5. scp the JAR
        run: scp -o StrictHostKeyChecking=no \
          -i ~/.ssh/id_rsa \
          target/*.jar \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/dormitory/dorm-api.jar

      - name: 6. Restart service
        run: ssh -o StrictHostKeyChecking=no \
          -i ~/.ssh/id_rsa \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "sudo systemctl restart dorm-api && sudo systemctl status dorm-api"
