# This workflow deploys the Spring Boot app to your server when you push to the main branch
name: Deploy Spring Boot App

on:
  push:
    branches: [ "main" ] # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # The pipeline runs on a fresh Ubuntu machine

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 3. Build the JAR file
        run: mvn -B package --file pom.xml

      - name: 4. Deploy and Restart via SCP/SSH
        run: |
            # Create a temporary file for the SSH private key
            echo "${{ secrets.SERVER_SSH_KEY }}" > private_key
            chmod 600 private_key
            
            # Deploy the JAR file using SCP
            scp -i private_key -o StrictHostKeyChecking=accept-new \
              target/dormitory-management-1.0.0.jar \
              ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/dormitory/dorm-api.jar
            
            # Restart the systemd service using SSH
            ssh -i private_key -o StrictHostKeyChecking=accept-new \
              ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
              'sudo systemctl restart dorm-api'
